-- Better Auth core schema for Postgres.
--
-- GENERATED by scripts/generate-auth-schema.mjs from the installed
-- better-auth. Do not hand-edit the tables above the chat-history block:
-- run `npm run auth:schema` after upgrading better-auth instead.
--
-- Identifiers are quoted because Better Auth uses camelCase columns.

CREATE TABLE IF NOT EXISTS "user" (
  "id" TEXT PRIMARY KEY,
  "name" TEXT NOT NULL,
  "email" TEXT NOT NULL UNIQUE,
  "emailVerified" BOOLEAN NOT NULL,
  "image" TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL,
  "updatedAt" TIMESTAMPTZ NOT NULL
);

ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "email" TEXT;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "emailVerified" BOOLEAN;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "image" TEXT;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMPTZ;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS "session" (
  "id" TEXT PRIMARY KEY,
  "expiresAt" TIMESTAMPTZ NOT NULL,
  "token" TEXT NOT NULL UNIQUE,
  "createdAt" TIMESTAMPTZ NOT NULL,
  "updatedAt" TIMESTAMPTZ NOT NULL,
  "ipAddress" TEXT,
  "userAgent" TEXT,
  "userId" TEXT NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE
);

ALTER TABLE "session" ADD COLUMN IF NOT EXISTS "expiresAt" TIMESTAMPTZ;
ALTER TABLE "session" ADD COLUMN IF NOT EXISTS "token" TEXT;
ALTER TABLE "session" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMPTZ;
ALTER TABLE "session" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMPTZ;
ALTER TABLE "session" ADD COLUMN IF NOT EXISTS "ipAddress" TEXT;
ALTER TABLE "session" ADD COLUMN IF NOT EXISTS "userAgent" TEXT;
ALTER TABLE "session" ADD COLUMN IF NOT EXISTS "userId" TEXT;

CREATE INDEX IF NOT EXISTS "session_userId_idx" ON "session" ("userId");

CREATE TABLE IF NOT EXISTS "account" (
  "id" TEXT PRIMARY KEY,
  "issuer" TEXT NOT NULL,
  "accountId" TEXT NOT NULL,
  "providerId" TEXT NOT NULL,
  "userId" TEXT NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE,
  "accessToken" TEXT,
  "refreshToken" TEXT,
  "idToken" TEXT,
  "accessTokenExpiresAt" TIMESTAMPTZ,
  "refreshTokenExpiresAt" TIMESTAMPTZ,
  "scope" TEXT,
  "password" TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL,
  "updatedAt" TIMESTAMPTZ NOT NULL
);

ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "issuer" TEXT;
ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "accountId" TEXT;
ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "providerId" TEXT;
ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "userId" TEXT;
ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "accessToken" TEXT;
ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "refreshToken" TEXT;
ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "idToken" TEXT;
ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "accessTokenExpiresAt" TIMESTAMPTZ;
ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "refreshTokenExpiresAt" TIMESTAMPTZ;
ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "scope" TEXT;
ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "password" TEXT;
ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMPTZ;
ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS "account_userId_idx" ON "account" ("userId");

CREATE TABLE IF NOT EXISTS "verification" (
  "id" TEXT PRIMARY KEY,
  "identifier" TEXT NOT NULL,
  "value" TEXT NOT NULL,
  "expiresAt" TIMESTAMPTZ NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL,
  "updatedAt" TIMESTAMPTZ NOT NULL
);

ALTER TABLE "verification" ADD COLUMN IF NOT EXISTS "identifier" TEXT;
ALTER TABLE "verification" ADD COLUMN IF NOT EXISTS "value" TEXT;
ALTER TABLE "verification" ADD COLUMN IF NOT EXISTS "expiresAt" TIMESTAMPTZ;
ALTER TABLE "verification" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMPTZ;
ALTER TABLE "verification" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMPTZ;

-- Chat history for signed-in accounts ---------------------------------------
--
-- Guests keep everything in their own browser and touch none of this. An
-- account exists so a conversation can follow you to another device, so these
-- two tables mirror the browser's IndexedDB stores closely enough that syncing
-- is a straight id-by-id comparison of updated_at.
--
-- deleted_at is a tombstone rather than a real delete: a chat removed on your
-- phone has to be removable on your laptop, and the laptop only finds out by
-- seeing the row.

CREATE TABLE IF NOT EXISTS chat_session (
  id            TEXT PRIMARY KEY,
  user_id       TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  title         TEXT NOT NULL DEFAULT 'New chat',
  title_locked  BOOLEAN NOT NULL DEFAULT FALSE,
  system_prompt TEXT NOT NULL DEFAULT '',
  temperature   DOUBLE PRECISION NOT NULL DEFAULT 0.7,
  pinned        BOOLEAN NOT NULL DEFAULT FALSE,
  created_at    BIGINT NOT NULL,
  updated_at    BIGINT NOT NULL,
  deleted_at    BIGINT
);

CREATE INDEX IF NOT EXISTS chat_session_user_idx
  ON chat_session (user_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS chat_message (
  id         TEXT PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES chat_session(id) ON DELETE CASCADE,
  user_id    TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  role       TEXT NOT NULL,
  content    TEXT NOT NULL,
  -- Attachment metadata only. The image bytes never leave the browser that
  -- picked them; see netlify/functions/chats.mts for why.
  meta       JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS chat_message_session_idx
  ON chat_message (session_id, created_at);
